version: '3'
services:
  postgres:
    image: postgres:12.2-alpine
    container_name: tic-tac-toe-postgres
    environment:
      - POSTGRES_DB=nakama
      - POSTGRES_PASSWORD=localdb
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5
    volumes:
      - data:/var/lib/postgresql/data

  nakama:
    build: .
    container_name: tic-tac-toe-nakama
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        /nakama/nakama migrate up --database.address postgres:localdb@postgres:5432/nakama
        exec /nakama/nakama --database.address postgres:localdb@postgres:5432/nakama
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    restart: on-failure

volumes:
  data:
