name: nakama-node
data_dir: "./data/"

logger:
  stdout: true
  level: "info"

console:
  port: 7351
  username: "admin"
  password: "password"

database:
  address:
    - "postgres:localdb@postgres:5432/nakama"

socket:
  server_key: "defaultkey"
  port: 7350

runtime:
  path: "/nakama/data/modules"
